version: "3"

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    expose: 
      - "5432"
    networks:
      - fullstack
  backend:
    env_file:
      - .env
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      - db
    networks: 
      - fullstack
networks:
  fullstack:
volumes:
  api:
  database_mysql:
      

