version: "3.9"

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=Library
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=JustReadTheInstructions
      - MYSQL_ROOT_PASSWORD=test1234
    ports:
      - "3306:3306"
    expose: 
      - "5432"
    networks:
      - fullstack
  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on: 
      - db
    networks: 
      - fullstack
networks:
  fullstack:
volumes:
  api:
  database_mysql:
      

